### ISSUE TITLE
Warning thrown for `disable_no_cache_headers_on_admin_ajax_nopriv()`. 

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/altis-cloud#114]
Altis 3 is throwing the warning: 

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'Altis\Cloud\Page_Cache\disable_no_cache_headers_on_admin_ajax_nopriv' not found or invalid function name in /chassis/wordpress/wp-includes/class-wp-hook.php on line 288

This is caused by the filter being registered in the wrong namespace, the function is `Altis\Cloud\disable_no_cache_headers_on_admin_ajax_nopriv()` but the filter specifies the `Altis\Cloud\Page_Cache` namespace.

**Comment by joehoyle** [comment]
Oops, I think that was  mistake when refactoring / moving namespces!

**Comment by roborourke** [comment]
Tagged 3.0.2 with this fix.
