### ISSUE TITLE
Add environment indicator to admin bar

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cloud#124]
Moved here from https://github.com/humanmade/altis-cms/issues/113

Acceptance criteria:

- [x] add a solution to differentiate environments via colour / other indicator
  - add the feature to a new namespace directory in the `inc` directory
  - evaluate https://github.com/tomjn/Local-Indicator for use, might be easier to use the approach from that and add the functionality directly here using `Altis\get_environment_type()` for example
- [x] indicator should show environment type in the top level menu item
  - indicator sub menu should show:
     - [x] the stack name
     - [x] a link to the stack on Altis dashboard (if env is not === local)
- [x] indicator should only show for admins or those with an `environment_indicator` capability

@Camila-villegas can you provide some guidance on the colours we could use to indicate the following environment types?

- local (safe to make any changes)
- development (unstable, safe to make changes and test things out)
- staging (semi-stable, used for client Quality Assurance mostly)
- production (exercise caution when making changes / edits etc)

TODO:
- [ ] Implement CSS when decisions on design are made
- [ ] Test Altis dashboard URL is correct for variety of environments (not sure how to do that on local - added by @dashaluna )

**Comment by roborourke** [comment]
Noted by @dashaluna the Local Indicator plugin looks like this by default:

![Local Indicator](https://user-images.githubusercontent.com/2185972/73377709-5cb47480-42b7-11ea-98f4-bc79fcb8edc9.png)

There are other design opportunities to consider here:

- could use a coloured border above the admin bar
- icon with a different colour to indicate environment type
- text makes it clearer what it means

**Comment by dashaluna** [comment]
@roborourke you ok closing this issues as PR has been merged? Don't think anything else is left.

**Comment by roborourke** [comment]
@dashaluna yep, nicely done here. For future PRs you can add the text “Fixes #xyz” to the PR comment and it’ll automatically close it when the PR is merged.
