### ISSUE TITLE
Log remote requests made by the AWS SDK

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cloud#125]
I'm seeing some huge perf issues where being able to dig into which AWS requests are made would be super useful. Because AWS SDK requests go via Guzzle rather than via WP_Http they're not currently logged.

(I know @johnbillion ran into similar things with Query Monitor's HTTP logging, so maybe there's some solution he saw there?)

**Comment by joehoyle** [comment]
Pretty sure there is a PR / branch on X-ray for this, as I put in a bunch of work on it

-- 

Joe Hoyle

CTO
Human Made

**Comment by johnbillion** [comment]
I looked at this very briefly for QM but it appears you can only do this if you can inject a logger into Guzzle when it's instantiated.

If there's a global event or interface that allows a logger to be injected by something other than the instantiatior then I'd love to know about it.

**Comment by rmccue** [comment]
As it turns out, yes, it was done for hm-platform in https://github.com/humanmade/aws-xray/pull/28

X-Ray [hooks into `hm_platform.aws_sdk.params`](https://github.com/humanmade/aws-xray/blob/dab5459648ac349f0904d39821c682b491d735a0/plugin.php#L23); that filter was [reverted](https://github.com/humanmade/hm-platform/pull/156) and never made it across to Altis.

We need to add a new filter into Altis Core to allow changing the SDK params, and use it in X-Ray.

**Comment by roborourke** [comment]
@dashaluna if you have time this week this a follow on from https://github.com/humanmade/altis-core/issues/66

We need to add this filter to the cloud module early enough to get applied:

```php
add_filter( 'hm_platform.aws_sdk.params', 'HM\\Platform\\XRay\\on_hm_platform_aws_sdk_params' );
```

Might need to go directly in `load.php` but do some experimenting, ideally add it to this file here 

https://github.com/humanmade/altis-cloud/blob/dee68f7cf1b19e06628c629002978c2d92b4bffe/inc/namespace.php#L25-L26

**Comment by roborourke** [comment]
Quick update here, currently trying to get this working on `platform-test` but not having much luck yet, The AWS SDK docs aren't so hot on examples.

WIP branch here: https://github.com/humanmade/platform-test/pull/20

**Comment by joehoyle** [comment]
@roborourke how were you providing credentials to the SDK btw? I just had to file https://github.com/humanmade/altis-core/pull/75.

So, locally at least (with the above fix) I get the remote request showing correctly in the Developer Tools Xray panel, are you seeing that @roborourke? I used the following test mu-plugin to cause the request:

```php
<?php

add_action( 'init', function() {
	Altis\get_aws_sdk()->createElasticLoadBalancingV2()->describeLoadBalancers();
});
```

Then I see it in the panel:

<img width="1552" alt="Screenshot 2020-02-10 at 4 25 44 PM" src="https://user-images.githubusercontent.com/161683/74191981-a2abf980-4c22-11ea-8207-3c45d5374c66.png">

**Comment by roborourke** [comment]
Ah cheers @joehoyle, I'll be honest I wasn't providing credentials, didn't realise it was necessary if there's a local xray container running. I was just looking in vantage on the platform test site.

**Comment by joehoyle** [comment]
Mm it's not required for Xray (and you don't need the xray container running), but you will need some credentials to get the AWS SDK to actually make a request -- though looks like you were running this on platform-test in the cloud, so that doesn't totally explain that.

**Comment by roborourke** [comment]
Maybe the logs are there then, just not being pulled in by vantage for some reason. Will see if I can confirm that
