### ISSUE TITLE
Visual bug with environment text on frontend

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cloud#129]
<img width="162" alt="Screen Shot 2020-02-05 at 15 04 14" src="https://user-images.githubusercontent.com/21655/73853472-d1902d00-4828-11ea-8497-39dcedfa7302.png">

From #124 and #126.

This is happening in Firefox (73b); may be due to Firefox's different handling of flex-basis.

**Comment by rmccue** [comment]
Removing the `flex: 0` rule fixes this, but unsure if it breaks anything else.

**Comment by roborourke** [comment]
Removing `flex: 0` will affect it on the backend. This is a weird flexbox bug in FF, def shouldn't cut the text off like that!
