### ISSUE TITLE
Healthcheck not available in JSON

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cloud#135]
We are intending to support fetching the `/healthcheck/` is JSON format too, by either specifying `Accept: appliction/json` or adding an `_accept=json` url param. Because CloudFront doesn't forward `Accept`, when wanting to fetch the Healthcheck externally, you'd expect to pass `?_accept=json` -- however that doesn't work because the condition to check the healthcheck is then not matched in https://github.com/humanmade/altis-cloud/blob/master/inc/healthcheck/namespace.php#L13 (`'/healthcheck/' !== $_SERVER['REQUEST_URI']`) ( `$_SERVER['REQUEST_URI']` includes query params).

We should be matching `/healthcheck/` by some means where query params are stripped. IMO while we are at it -- allow `/healthcheck` (no trailing slash) to also match.

---------------

Acceptance criteria:

- [ ] Healthcheck can be accessed via `/__healthcheck` or `/__healthcheck/` with any query string
- [ ] If the header `Accept` has the value `application/json` return a JSON response
- [ ] If the query string contains `_accept=json` return a JSON response
- [ ] The response should look like the following:
  ```json
  {
	"status": "failed | ok",
	"checks" : {
		"mysql": {
			"status": "ok | failed",
			// only add the error if the check returned a WP_Error
			"error": {
				"code": "error code",
				"message": "error message"
			}
		},
		"...": "..."
	}
  }
  ```

**Comment by rmccue** [comment]
We should rename it to something less generic while we're there, like `__healthcheck` or `altis-healthcheck`. Given we're not using it extensively, we should be fairly safe to rename it.

**Comment by ivdimova** [comment]
Actually the healthcheck is available in json, as far as I see - https://github.com/humanmade/altis-cloud/blob/master/inc/healthcheck/namespace.php#L38. I have done a PR for the rest of the acceptance criteria @roborourke

**Comment by roborourke** [comment]
@ivdimova it was in theory but the code checking the `/healthcheck` URL didn't account for query strings, so that was never working.
