### ISSUE TITLE
Add instance healthcheck to be used for ALB healthcheck

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cloud#159]
Currently our ALB (or specifically Target Group) healthcheck sends requests to `wp-admin/install.php` to check for 200 responses. This is a healthcheck to determine if a specific instance is healthy, not the whole application (which is what `/__healthcheck` is for).

The _instance healthcheck_ needs to determine if PHP is functioning correctly on the specific instance, and currently, not much else. Rather than rely on `wp-admin/install.php` for this, which is not built this for this purpose, we should introduce a new path of `/__instance_healthcheck` that works similat to the current `/__healthcheck` but only checks things that could be a problem with the current server. Currently that would just be "return true", because if PHP has managed to execute our `/__instance_healthcheck`, then that's about all the checking we currently need.

In the future we may want to add other checks too, so we should use the same code patterns as `/__healthcheck` and I'd recommend we just co-locate the code for both in the same place.

I think it would be good to also exclude requests to this URL from AWS Xray as they are not public web requests, and often get in the way when trying to debug things.

cc @humanmade/servers if this sounds appropriate, as once this change is in Altis, we'll want to update terraform-app-stack too.

-------------

Acceptance criteria:

- [ ] The URL `/__instance_healthcheck` or `/__instance_healthcheck/` should return an empty response
- [ ] The HTTP response code should be 200

**Comment by nathanielks** [comment]
Yup, mostly sounds good to me 👍 With not including X-Ray, so I'd like to ensure we have verbose error logging in that endpoint (should it ever include more than `return true;`.

**Comment by roborourke** [comment]
@joehoyle I updated this with some acceptance criteria - can you confirm that's correct and edit if needed?

**Comment by joehoyle** [comment]
Looks good!

**Comment by ivdimova** [comment]
I see the `healthcheck` works as a `wp cli` command as well, should there be another command for `instance healthcheck`?

**Comment by joehoyle** [comment]
@ivdimova good catch, i think we might as well for constistency yeah! 👍

**Comment by roborourke** [comment]
Done in #171
