### ISSUE TITLE
Tachyon domain to be current domain on multisite

### ISSUE THREAD

**Issue by stuartshields** [humanmade/altis-cloud#170]
So currently if we have a multi-site setup like the following:
blog.us.example.com (main site)
blog.au.example.com (site id 3)
blog.uk.example.com (site id 4)

Tachyon will do the URLs as follows:
blog.us.example.com/tachyon/2020/04/example.jpg
blog.us.example.com/tachyon/sites/3/2020/04/example.jpg
blog.us.example.com/tachyon/sites/4/2020/02/example-2.jpg

Ideally whatever the current domain is, the Tachyon URL should match:
blog.us.example.com/tachyon/2020/04/example.jpg
blog.au.example.com/tachyon/sites/3/2020/04/example.jpg
blog.uk.example.com/tachyon/sites/4/2020/02/example-2.jpg

Currently we'd do something like this
```
if ( strpos( $_SERVER['HTTP_HOST'], 'example.com' ) !== false ) {
	$base_url = 'https://' . $_SERVER['HTTP_HOST'];
	define( 'TACHYON_URL', $base_url . '/tachyon' );
}
```

However it'll make sense to do this by default within Altis-Media and not have to worry about doing this at a server level for each project.

**Comment by rmccue** [comment]
Moved across to the cloud repo; fwiw, I think Tachyon probably should be in media, and it's more of a historical quirk that it's not.

There's no particular reason for the domain, apart from consistency across the network, and it's easier to have a single constant. Potentially this would affect cache hit rates if images are used cross-site, but I doubt that's actually ever an issue anyway.

@joehoyle any reason for us to not make this current-domain-based?

**Comment by joehoyle** [comment]
This was done like so to provide a consistent domain / urls across sites. That was an intentional decision. As the path of the image is already in `sites/$siteid`, it's duplicative to have the whole network's images available on _all_ sites. Though this is still possible (by doing what you did) I'd recommend against it unless there is specific reason why you'd want to do that. Images should canonically be in one place, and that place is `sites/$siteid`. So, I think we have a good default here.

**Comment by rmccue** [comment]
The disadvantage is cross-domain image requests when working with multisite, which I think is a concern that we want to address.

**Comment by joehoyle** [comment]
Hmm perhaps -- if you have say, Mercator, or just even lots of different first-class domains, I still don't think it's a good default to necessarily serve from that domain. For example, United Bloggers: all images come from the "platform" domain, and each user's site is for things specific to them.

**Comment by Kenshino** [comment]
@joehoyle what about the possibility of clients with multiple entities sharing the same platform and each entity is separated via locales?

e.g. com.sg, .com, .co.uk, .co.jp for example?

It wouldn't make sense for the UK entity to be serving Japanese images

**Comment by joehoyle** [comment]
@Kenshino in that case you can do the custom thing that @stuartshields mentioned. This is only about defaults, and I think a better default is to consider the sites as a group fairly closely related. We support both approaches.

One issue we do have right now is that any image on any site can be accessed via another site's domain. You can show a JP image from the US domain, though it's never linked to, it's possible.

**Comment by Kenshino** [comment]
Could we look at offering what @stuartshields did as an option within Altis but not the default?

**Comment by stuartshields** [comment]
@joehoyle From what I can gather from the discussion above and correct me if I'm wrong:
We actually want to do something like:
`blog.au.example.com/tachyon/2020/02/example.jpg` which only serve the AU image and nothing else.

OR even:
`example.com.au/tachyon/2020/02/example.jpg`

Could one way we do this is to apply something like:

- Tachyon URL: [x] Main domain [ ] Current domain

Rules for this would be:
If the setting is the Main domain, we serve across the board which is what currently happens:
- blog.us.example.com/tachyon/2020/04/example.jpg
- blog.us.example.com/tachyon/sites/3/2020/04/example.jpg
- blog.us.example.com/tachyon/sites/4/2020/02/example-2.jpg

Current domain would be:
- blog.us.example.com/tachyon/2020/04/example.jpg (only US images)
- blog.au.example.com/tachyon/2020/04/example.jpg (only AU images)
- blog.uk.example.com/tachyon/2020/02/example-2.jpg (UK images)

I use blog.au.example.com as an example but it could also be:
- example.com/tachyon/2020/04/example.jpg (only US images)
- example.com.au/tachyon/2020/04/example.jpg (only AU images)
- example.co.uk/tachyon/2020/02/example-2.jpg (UK images)

Upon writing the above, the only time that I could see `Main Domain` overwriting the rules of `Current Domain` is when subdirectory is used. Since we allow for Subdomain, Subdirectory and Custom domain, I'm not entirely sure we need the settings, we just set the URL programmatically depending on what rules are hit.

Thoughts on the above? I'm happy to give what I envision a go and get feedback from there on if it'd work.

**Comment by joehoyle** [comment]
>  blog.au.example.com/tachyon/2020/02/example.jpg which only serve the AU image and nothing else.

Yeah, so this is not possible. Though we support accessing `/tachyon` on any domains on the network, you still have to use the full path `/sites/$id/`. That is not avoidable, unfortunately.

To be able to do such a mapping of domain => site-id path, Tachyon would need to know "what site ID is this domain for"... which it does not. Figuring that out needs access to the WordPress database, and is beyond the scope of Tachyon (which is decoupled from WordPress).

If having all the images available on that path is not an option, I don't think the "use a single stack for all sites" is perhaps the best approach for what you are trying to do.

**Comment by joehoyle** [comment]
@stuartshields can this be closed out? I think the tl;dr here was that you didn't want to just change the domain, but also the paths, so `/uploads/` is scoped per-site, which is not possible.

**Comment by stuartshields** [comment]
@joehoyle So I'm going to close this, but it doesn't matter about `/uploads/` it was more just to show the current blog url.
