### ISSUE TITLE
Add final filtered query into X-Ray

### ISSUE THREAD

**Issue by Nikschavan** [humanmade/altis-cloud#183]
The query which is built from the application code is being tracked to X-Ray - 

https://github.com/humanmade/altis-cloud/blob/a8c4eb12098b344df9843e8c51e4806935653a35/inc/class-db.php#L65

When this query is being executed in `WPDB::query` it is passed through the filter [`query`](https://github.com/WordPress/WordPress/blob/8d1e51e9c769ec57375efb39b72cac2c3abf8108/wp-includes/wp-db.php#L1894) which removes placeholders at the very least and it is also possible that queries can be modified altogether using this filter.

Since when sending the query to X-Ray does not take into account the filter we don't get the actual query that was executed. 

Running filter `query` just before sending it to X-Ray should hopefully fix this.

**Comment by roborourke** [comment]
This might be intentional as a means of making sure the query is redacted as it could potentially show email addresses and such. We already redact some data before sending it to XRay so we need to make the same consideration here, I'm not sure it's as simple as changing the hook.

**Comment by Nikschavan** [comment]
I only noticed one of the PRs with redactions in X-Ray - https://github.com/humanmade/aws-xray/pull/34

If we run this filter, [WordPress's functions to replace the placeholders](https://github.com/WordPress/WordPress/blob/32edd58e4c8e42b68813e3b92886aaa3e50cc1a9/wp-includes/wp-db.php#L2104) gets executed and removes the placeholders.

I did not find any query redactions atm, Can you point me to ones I am missing so that I can check if these are working as expected with this change?

**Comment by rmccue** [comment]
These escapes aren't redactions, they're just placeholders for the `%` character so it survives any `sprintf` calls without being mangled. We can safely change those back.

**Comment by jennybeaumont** [comment]
This was completed
