### ISSUE TITLE
Queue purge media cache when rate limited.

### ISSUE THREAD

**Issue by stuartshields** [humanmade/altis-cloud#186]
@joehoyle So I ran into an issue that will cause issues for other projects I believe with using:
https://github.com/humanmade/altis-cloud/blob/master/inc/cloudfront_media_purge/namespace.php#L29

```
TooManyInvalidationsInProgress (client): Processing your request will cause you to exceed the maximum number of in-progress wildcard invalidations. 
```

@Japh suggested that we need to queue this so we aren't rate limited by AWS.

Thoughts?

**Comment by stuartshields** [comment]
We also get the following as well not sure if related:
```
InvalidArgument (client): Your request contains a caller reference that was used for a previous invalidation batch for the same distribution.
```

**Comment by joehoyle** [comment]
@stuartshields it looks like you might be sending too many invalidation requests at once. When you want to purge an attachment, are you doing one purge request per file, or passing them all at once?

I'll look into what the rate limit is too.

**Comment by joehoyle** [comment]
Per the AWS docs, this is the limits:

> If you’re invalidating files individually, you can have invalidation requests for up to 3,000 files per distribution in progress at one time. This can be one invalidation request for up to 3,000 files, up to 3,000 requests for one file each, or any other combination that doesn’t exceed 3,000 files. For example, you can submit 30 invalidation requests that invalidate 100 files each. As long as all 30 invalidation requests are still in progress, you can’t submit any more invalidation requests. If you exceed the maximum, CloudFront returns an error message.

> If you’re using the * wildcard, you can have requests for up to 15 invalidation paths in progress at one time. You can also have invalidation requests for up to 3,000 individual files per distribution in progress at the same time; the maximum on wildcard invalidation requests allowed is independent of the maximum on invalidating files individually. 

@stuartshields could you detail how many concurrent invalidations you are trying to do? Is this "normal operation", or are you running a migration or something that's causing a lot of requests?

**Comment by stuartshields** [comment]
@joehoyle So I found an issue that when it was saving it was hitting the AWS function 4~ times. I think this will solve the issue somewhat. 

Will we hit the rate limit if the post has say 20 attachments?

**Comment by joehoyle** [comment]
@stuartshields Hmm if you are using `purge_media_file_cache()` yes, that will have a concurrency limit of 15 I think. You could use `Altis\Cloud\purge_cdn_paths()` directly (if you are not now) to invalidate up to 3k absolute paths too, but I think the wildcard approach is probably more what you want.

Also `purge_media_file_cache()` will actually do _two_ wildcard invalidations per attachment (so the limit is more like 7 attachments at once) because it has to do one for `/uploads/*` and one for `/tachyon/*`. We could probably optimize this to only do a wildcard one for `/tachyon/` and then do a fixed-file one for all the different attachment files.

It sounds like the 4x reduction with the bug you found will help, but we need to come up with a fix in altis-cloud too to workaround the concurrency issues.

**Comment by stuartshields** [comment]
Thanks @joehoyle, I believe my issue is related to `transition_post_status` firing twice because of the REST API.

**Comment by rmccue** [comment]
Is there anything further to be done here for v4 @joehoyle?

**Comment by joehoyle** [comment]
@rmccue I'm worried that the current concurrency limit is going to be an issue. At the moment you can basically only call `purge_media_file_cache` 7 times in a script execution, so something like deleting a bunch of attachments will fail.

Only way around this I can see is to doing it async, and have a cron to do them in batches or something, but that doesn't seem ideal either.

**Comment by rmccue** [comment]
(Per [Slack discussion](https://hmn.slack.com/archives/C3CKS8LLR/p1592569705062000):) For v4, we're going to accept that this is a known limitation, and consider fixes for v5. We'll document that limitation in the meantime.

**Comment by rmccue** [comment]
We handled this in https://github.com/humanmade/altis-cloud/pull/197
