### ISSUE TITLE
Port the cloud UI over

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cloud#19]
We may want to port the work done on the platform cloud UI over to this repo. I'm not sure if this should happen for v1 but there's a bunch of prior art here already.

Key aspects of the cloud UI

1. Displays a subset of Vantage data
1. Deep links to Vantage based on current stack
1. Support information and links

We could at a minimum cover points 2 & 3 from the above.

I personally feel it can be useful to have this information in multiple places so that there's information in a developer / site owner's current context.

Thoughts on this @joehoyle @rmccue ?

**Comment by rmccue** [comment]
Per @roborourke, we can handle this in a different way. If we decide to reuse the code, we still can, but it should be driven by user need.
