### ISSUE TITLE
Condition is always true

### ISSUE THREAD

**Issue by pdewouters** [humanmade/altis-cloud#208]
**Describe the bug**
The condition here https://github.com/humanmade/altis-cloud/blob/master/inc/namespace.php#L694
`$request->getStatusCode() !== '200'`

Looking at the docs for `getStatusCode` it returns an `int` so the strict comparison would always be true?

**Comment by roborourke** [comment]
@pdewouters good catch! That should definitely ensure the types match. Are you able to PR the fix?

**Comment by roborourke** [comment]
Fixed in #210
