### ISSUE TITLE
Error in ElasticSearch request

### ISSUE THREAD

**Issue by stuartshields** [humanmade/altis-cloud#212]
Currently we are seeing a bunch of errors created by Elastic Search in Altis Cloud.

```
[10-Jul-2020 04:10:26 UTC] PHP Warning:  Error in ElasticSearch request:  (0) in /usr/src/app/vendor/altis/cloud/inc/namespace.php on line 329
```

Reference in code:
https://github.com/humanmade/altis-cloud/blob/master/inc/namespace.php#L329
```
if ( ! defined( 'ELASTICSEARCH_HOST' ) || ELASTICSEARCH_HOST !== $host ) {
```

**Comment by roborourke** [comment]
@stuartshields was there nothing else appended to that error message? There should be either WP Error information or a JSON error response from Elasticsearch. I can't really begin to try and resolve this without that info. You can message in slack if there's any context / detail needed to be kept private.

**Comment by jennybeaumont** [comment]
@stuartshields heya 👋 is this still an issue? If so, could you respond to Rob's question above? If no news going to close this out. Thanks!

**Comment by roborourke** [comment]
Not really enough info to go on here - there could be many reasons for it so closing this out. Reopen if more information / detail becomes available.

**Comment by ntwb** [comment]
Just to comment, and I've not much additional to share, but I see similar whilst running the following:

```shell
$ wp aws-rekognition update-keywords --url=example.com/gallery
Warning: Error in ElasticSearch request:  (0) in /usr/src/app/vendor/altis/cloud/inc/namespace.php on line 344
Warning: Error in ElasticSearch request:  (0) in /usr/src/app/vendor/altis/cloud/inc/namespace.php on line 344
Warning: Error in ElasticSearch request: 403 Request throttled due to too many requests /example.com/gallery-81/post/_search (403) in /usr/src/app/vendor/altis/cloud/inc/namespace.php on line 344
Warning: Error in ElasticPress request: 403 Request throttled due to too many requests /example.com/gallery-81/post/_search (403) in /usr/src/app/vendor/altis/enhanced-search/inc/namespace.php on line 213
Warning: Error in ElasticSearch request:  (0) in /usr/src/app/vendor/altis/cloud/inc/namespace.php on line 344
Warning: Error in ElasticSearch request:  (0) in /usr/src/app/vendor/altis/cloud/inc/namespace.php on line 344
```

In that cli output there were 40 requests with the 403, and 455 instances where the response wasn't available and only returned `(0)`.

Nothing obvious in the Altis Dashboard logs or xray either unfortuanately

As such, not reopening but documenting here for reference.
