### ISSUE TITLE
Document migration processes and expectations

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cloud#222]
Migrations onto the platform and between given environments come with certain processes that we should aim to follow, as well as expectations around lead time, scheduling, etc. We should document these in a clear way to make expectations clear, and have a point of reference.

This should be documented in the Playbook. We want to get ahead of the back-and-forth communications so that we can frontload the communication, and make sure everyone is on the same page with what's required.

Ahead of time, we should know:

* Who controls the DNS?
* Where are we migrating the data from?
* Size of database
* Possibly more?

----
*Previous description:*

Specifically, I think we should document:

* ~Standard user-facing procedures, such as content freeze (and when such a thing is required)~ Handled in https://github.com/humanmade/altis-documentation/issues/125
* Standard back-of-house procedures for context
* ~Required lead time on performing migrations~
* ~Scheduling expectations and how we deal with exceptions~

**Comment by nathanielks** [comment]
> Scheduling expectations and how we deal with exceptions

Eg preferring to perform migrations during the week and making exceptions for weekends when necessary.

**Comment by rmccue** [comment]
This now appears to be a duplicate of https://github.com/humanmade/product-dev/issues/732 so closing.
