### ISSUE TITLE
PHP Warning in environment_indicator/namespace.php

### ISSUE THREAD

**Issue by pdewouters** [humanmade/altis-cloud#236]
Found these warnings in the logs on yell-dev-01

```
[13-Aug-2020 10:27:25 UTC] PHP Warning:  Creating default object from empty value in /usr/src/app/vendor/altis/cloud/inc/environment_indicator/namespace.php on line 63undefined
```

**Comment by Nikschavan** [comment]
@roborourke - Any idea who this can be fixed? This warning appears on each reloads in the wp-admin.

The warning only happens when the `branding` module is disabled so the `altis` node does not exist on the `wp_admin_bar`.

I was thinking if we just add a new empty node `altis`  if it does not exist? Happy to send a PR once the approach is finalized.

**Comment by roborourke** [comment]
I think we just check if the node is there rather than adding an empty node. So if `$node` is falsy just return early - I think we can try getting the node earlier in the function.

**Comment by Nikschavan** [comment]
So you mean to disable the environment indicator if the node does not exist? (i.e. if the branding module id disabled)

The environment indicator is a good addition so I was hoping to have it still enabled. Right now this throws the warnings but the env indicator is still displayed.

**Comment by roborourke** [comment]
Ideally you could just turn the branding on but if you’d like to keep the functionality then I guess we can identify a fallback node like the WP logo node 🤔

**Comment by Nikschavan** [comment]
> Ideally you could just turn the branding

This actually was a request from the client to disable branding so we had to disable this.

WP Logo node does work but the label stays squeezed with the logo - 

![image](https://user-images.githubusercontent.com/2931091/98523568-135c7100-229c-11eb-95e7-bd22c1dd8eec.png)

I was thinking something like this if the node does not exist register and get the new arbitrary node for this particular case - 

```PHP
if ( ! is_object( $node ) ) {
	$env_indicator_args = [
		'id'    => 'altis-env-indicator',
	];

	$wp_admin_bar->add_menu( $env_indicator_args );
	$node = $wp_admin_bar->get_node( 'altis-env-indicator' );
}
```

This keeps the UI consistent for the environment indicator -

![image](https://user-images.githubusercontent.com/2931091/98523952-8ebe2280-229c-11eb-8131-24ae3906332c.png)


I am fine with both approaches, do let me know and I can send a quick PR :)

**Comment by roborourke** [comment]
Your suggested approach looks better to me, lets go with that.

**Comment by roborourke** [comment]
I'll get this released soon, thanks for the update @Nikschavan !

**Comment by roborourke** [comment]
This is now released, update to the latest patch version to get the change
