### ISSUE TITLE
Consider sending healthchecks to Xray

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cloud#246]
In https://github.com/humanmade/altis-cloud/pull/243 we removed healthchecks being sent to X-Ray as they pollute the requests and statistics. We could still send them to their own service name if we wanted, like `{app-name}-healthchecks`. This sound mean in the rare cases where we want to debug the healthchecks it would allow for that.

**Comment by rmccue** [comment]
Seems like a stretch of a could have, closing for now.
