### ISSUE TITLE
Documentation is missing all extensions

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cloud#262]
The [Cloud specifications page](https://www.altis-dxp.com/resources/docs/cloud/specifications/) is missing at least the redis extension, and may be missing others.

We should synchronise this with the list [from the Dockerfile source](https://github.com/humanmade/docker-wordpress-php/blob/master/Dockerfile#L70).

**Comment by jennybeaumont** [comment]
Is this intentional? First step to do a sweep and understand what might be needed.
