### ISSUE TITLE
WP 5.2 Site Health Check Compat

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cloud#28]
In WP 5.2 there's a new site health check feature that runs some automated tests to check things are working.

As this includes features such as background updates we'll need to disable those tests that aren't compatible with our infrastructure.

https://make.wordpress.org/core/2019/04/25/site-health-check-in-5-2/

In addition we could add our own tests, eg. exposing our custom healthcheck data for DB, ES and Cavalcade to admins as well.

**Comment by joehoyle** [comment]
We probably need to assess whether our own healtheck plugin is worth continue with, or can they be migrated to this. Our healthcheck is meant to be externally accessible and machine readable, so would need to make sure the Core one can do that.

**Comment by pdewouters** [comment]
Would there be 2 tasks here: 

1. customize the WP core health checks, by removing unwanted tests and adding our own ( in this case both would coexist until 2 is implemented)
2. Replacing our healthcheck page with the output of customimsed core WP healthcheck

**Comment by rmccue** [comment]
> Or do we only want to do the work if we can substitute our existing healthcheck?

I suspect so, yes, otherwise we should just disable core's.

**Comment by roborourke** [comment]
Moving this to icebox for now, we should re-assess down the line but it's not crucial in the shorter term and needs more research to determine what we actually want to do.

**Comment by jennybeaumont** [comment]
Closing. WP health check is disabled.
