### ISSUE TITLE
Ensure clients understand pullrequest flow - and how we're notified.

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/altis-cloud#290]
If a PR gets assigned to cloud we are notified at the point of assignment. If we review the PR and it does not get merged, and later new commits are pushed, our notification system isn't aware of that, so it's possible the PR falls through a crack in the system. 

We need to fill this crack so that the proper flow is understood and followed

We either need to:
1) Ensure clients understand how the flow works for assigning PR's and how it works in regard to how we get notified. 
2) Modify how our notifications work so we can be re-notified. 
3) Add automation to our flow which can add automated follow up messages which describes the next steps to the PR requester as to what happens next in the flow.

For background:
https://hmn.slack.com/archives/C5WSNGC9F/p1606313772496700

**Comment by rmccue** [comment]
We replaced the review flow with ACR and our docs cover this.
