### ISSUE TITLE
Getting URLs for S3 uploaded attachments involves repeatedly switching blogs 

### ISSUE THREAD

**Issue by goldenapples** [humanmade/altis-cloud#312]
I've noticed that the "query-attachments" admin ajax request on subsites in a multisite network takes sometimes 10-20 seconds to return results. This is most noticeable when opening the media library on a non-primary site - especially when Smart Media is active, because the cropper will return attachment URLs for each defined crop size of all 40 attachments returned per page. 

The slowest part of this process by far is the `Altis\Cloud\set_s3_uploads_bucket_url_hostname` function, which is hooked on "upload_dir". This filter takes on average 28ms to run, and it runs for every crop size for every image in the query results. In the x-ray trace I'm looking at ([1-602d3f5d-6bda22f81ccdd1901f4b08d2](https://dashboard.altis-dxp.com/#/us-east-1/playstation-prod-01/xray/trace/1-602d3f5d-6bda22f81ccdd1901f4b08d2)) this is being called 320 times (40 images in the results x 8 crop sizes each). 

I suspect that the cache thrashing caused by repeatedly switching blogs as part of the [`get_main_site_url()` function](wp-includes/cache.php) may be causing this performance hit. We should be able to cache the main site URL when first retrieved rather than switching blogs each time we need to build an s3 bucket URL.

**Comment by roborourke** [comment]
This is my fault, there was an expectation that tachyon & uploads URLs would just work and match the site's host name whereas previously they were configured from environment variables related to the stack, see issue #217 and PR #218 for context.

We definitely want to avoid switching blogs.

**Comment by roborourke** [comment]
Thanks @goldenapples, this is now available in the following releases: 4.0.15, 5.0.7 and 6.0.2

**Comment by goldenapples** [comment]
Thanks so much for helping out with this @roborourke!
