### ISSUE TITLE
ELASTICSEARCH_PORT is appended to ELASTICSEARCH_HOST which causes a redirect to occur

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cloud#360]
I noticed that when an ES query runs that it first responds with a redirect in order to remove the `:443` port from the URL. This adds unnecessary overhead.

Screenshot from Query Monitor when loading the dashboard of a site and a query is triggered by `Altis\Analytics\Audiences\get_field_data()`:

<img width="1077" alt="Screenshot 2021-04-14 at 13 33 16" src="https://user-images.githubusercontent.com/208434/114711904-c93a5880-9d2f-11eb-81a9-216ca97f7851.png">

This seems to be caused by `\Altis\Cloud\get_elasticsearch_url()` appending `ELASTICSEARCH_PORT` to the URL.

**Comment by johnbillion** [comment]
I'll also need to double check that WP / cURL / QM are correctly reporting this as a redirect, there's a chance that it's not actually redirecting but being reported as one.

**Comment by roborourke** [comment]
This has been reported before but I'm pretty sure WordPress normalises the URL to remove ports `80` or `443` before making any requests. We could do this ourselves though before defining the constant.
