### ISSUE TITLE
SES to Cloudwatch fails when email has attachment bigger than 64Kb

### ISSUE THREAD

**Issue by ivankristianto** [humanmade/altis-cloud#371]
So while debugging the issues on intermittent errors with email not delivered.
See this ticket:
- https://dashboard.altis-dxp.com/#/support/ticket/4873/

I suspect this is because monolog use UDP when sending the package, max packet size is 65,535 bytes.

Steps to reproduce:
1. Go to any environments in Altis cloud, from the CLI command, try send wp_mail with attachment larger than 64Kb.
2. No email has been logged in the Email log altis dashboard

Expected:
I expect to see email is logged, success/failed, without attachment if it is a limitation.

Screenshots:
I have bunch of screenshots in this ticket: https://dashboard.altis-dxp.com/#/support/ticket/4873/

Acceptance criteria:

- [ ] ...

**Comment by rmccue** [comment]
Updated to remove client details.
