### ISSUE TITLE
LudicrousDB constants undefined when we load the class directly

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-cloud#388]
Steps to reproduce:
1. On an Altis 6 environment running PHP 7.2 (should happen on 7.4 as well), trigger a database query that responds with an unknown lagged status (I don't actually know how to reliably replicate this, but I see it happen with some regularity today on a production environment.)

Where I would expect for the ludicrousdb dropin to work as expected without logging any warnings, instead we are getting a warning in the logs,

```
PHP Warning:  Use of undefined constant DB_LAG_UNKNOWN - assumed 'DB_LAG_UNKNOWN' (this will throw an Error in a future version of PHP) in /usr/src/app/vendor/humanmade/ludicrousdb/ludicrousdb/includes/class-ludicrousdb.php on line 788
```

This is happening because we require `ludicrousdb/includes/class-ludicrousdb.php` directly inside `load_db()` in `inc/namespace.php`. In the out-of-the-box LudicrousDB dropin, the plugin will also load `includes/functions.php` and call the function `ldb_default_constants()` to define constants prior to any further action. If that flow is followed, `DB_LAG_UNKNOWN` will resolve to `3` and no undefined constant warning will be triggered.

We should pull in this file and run that constants definition function so that logs do not get polluted with these warnings.

**Comment by roborourke** [comment]
Thanks @kadamwhite!
