### ISSUE TITLE
Provide more information about geo-targeting value format

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cloud#398]
Ref: https://docs.altis-dxp.com/cloud/geo-targeting/

This page doesn't provide any information about what the format of the value in the `HTTP_CLOUDFRONT_VIEWER_COUNTRY` header is.

It looks like it's ISO 3166-1 Alpha-2 but this needs confirming.

Technical detail as well as some example codes would make this page clearer.

**Comment by rmccue** [comment]
`HTTP_CLOUDFRONT_VIEWER_COUNTRY` is the PHP-specific name of the `CloudFront-Viewer-Country` header, which is documented here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-cloudfront-headers.html#cloudfront-headers-viewer-location - it is indeed ISO 3166-1 alpha-2.

**Comment by johnbillion** [comment]
Thanks. Adding a link to that page would probably suffice.
