### ISSUE TITLE
Update wp-redis upstream, with support for wp_cache_get_multi

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cloud#399]
About a year ago, Core added some good performance optimizations in the object cache, by starting to use `wp_cache_get_multiple` (see https://github.com/WordPress/WordPress/commit/8a6cc1a810d26e2dd2375592ec74d4cc32f811f9)

Our forked version of wp-redis does not have this in it, so we should probably either switch to the pantheon upstream directly (if we don't need our fork any more), or we should merge upstream in to `humanmade/wp-redis`.

Acceptance criteria:
* [x] Update plugin to latest version
* [ ] Switch to upstream instead of our fork if it makes sense
* [x] Investigate statistics on performance improvements from before/after
* [x] Update any relevant docs (if they exist)

**Comment by joehoyle** [comment]
I had a look at our repo https://github.com/humanmade/wp-redis/commits/master and it doesn't look like we have modifications, apart from the packagist location. Also https://github.com/pantheon-systems/wp-redis/releases looks like the delta doesn't include any breaking changes.

**Comment by tcrsavage** [comment]
+1
There is a fairly significant performance improvement to be had here in cases where a large collection of post objects is queried.

The optimisations now baked into WP_Query actually cause significant performance costs without cache_get_multi implemented, as term data is pre-cached by default


![Screenshot 2021-06-16 at 08 19 55](https://user-images.githubusercontent.com/907521/122175982-00d29780-ce7c-11eb-85c3-a9b07f95a5d9.png)

**Comment by shadyvb** [comment]
@roborourke do we need to update any docs in this case ?
