### ISSUE TITLE
Add locking implementation

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cloud#41]
We should have a way to acquire mutexes (aka locks) using our underlying implementations. With Redis in particular, we should use the [Redlock algorithm](https://redis.io/topics/distlock) if we have multiple instances; if it's just the one, we can use the naive implementation instead.

**Comment by rmccue** [comment]
@rmccue to clarify.

**Comment by jennybeaumont** [comment]
@rmccue could you please add clarification, or close if no longer needed? thnx!

**Comment by rmccue** [comment]
Haven't seen the need for this lately, and no huge demand. Closing; we can pick up the idea some time in the future.
