### ISSUE TITLE
Warn when using `wp_upload_dir()` too early

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cloud#421]
S3 Uploads is loaded on the `plugins_loaded` hook early so we need to warn developers trying to use `wp_upload_dir()` before S3 uploads has rewritten the paths.

Acceptance criteria:

- [x] Warn using `_doing_it_wrong()` if S3 uploads has not been initialised when calling `wp_upload_dir()`
- [x] Avoid caching uploads directory in `Altis\Cloud\set_s3_uploads_bucket_url_hostname` if called too early
- [x] Avoid caching uploads directory in `Altis\Cloud\set_s3_uploads_bucket_url_hostname` if the directory is a local path instead of an S3 path

**Comment by rmccue** [comment]
Related: https://github.com/humanmade/S3-Uploads/issues/540
