### ISSUE TITLE
Clarify MySQL version

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cloud#482]
[The Specifications page](https://docs.altis-dxp.com/cloud/specifications/) lists the MySQL version as `5.6, 5.7`. It's not clear why two versions are listed here. Which is in use?

_Edit:_ Apparently Aurora is in use, not vanilla MySQL. This should be clarified too.

**Comment by veselala** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-cloud/482?planning-poker) with Zenhub @ferschubert-hm @jerico @kovshenin @mikelittle @sivanovhm @wisyhambolu
