### ISSUE TITLE
Add ability for multiple DB Read Replicas

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-cloud#51]
To better scale our databases, I'd like the ability to add multiple read-replicas. Before I get started on implementation, I'm curious how you'd want to handle it here:

https://github.com/humanmade/altis-cloud/blob/d1c14c918cec5a4ee956d5d6d910804afc7c4b2b/inc/namespace.php#L254-L263

As far as populating `DB_READ_REPLICA_HOST`, it could be a simple comma delimitated string. Question is: do we update the implementation here to break on a comma and iterate over the hosts and add them, or do we introduce a plural version of the aforementioned constant and loop over that?

**Comment by joehoyle** [comment]
My understanding of aurora is that there’s only ever 1 reader endpoint even with multiple read replicas?

-- 

Joe Hoyle

CTO
Human Made

**Comment by nathanielks** [comment]
You sir, are correct! I was not aware of this. Cheers!
