### ISSUE TITLE
Elastic requests debugging can result in empty messages.

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-cloud#544]
One support request identified an error message that doesn't include relevant information. The message is supposed to debug when a request to Elastic has failed, and include relevant error code and message to enable developers to further debug the issue and understand the failure reason.

The error is logged at https://github.com/humanmade/altis-cloud/blob/9.0.0/inc/namespace.php#L379.

The problem is that the `$response` can sometimes be a non-error, yet not have a non-2xx status codes, or not be an array at all, so we need to account for all possible cases to allow developers to debug such cases.

**Comment by joehoyle** [comment]
Closing as wontfix / toonicetohave
