### ISSUE TITLE
Expose environment variables for build scripts

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-cloud#591]
### Context

Clients might need to customize build scripts based on the environment and/or the branch being deployed.

### Acceptance criteria

- [x] Update our Node.js CodeBuild environment variables to match our PHP/WP variables (to include GIT_BRANCH and STACK_NAME)
- [x] As a customer, I can use $GIT_BRANCH and/or $STACK_NAME to customize my build script for different environments.
- [ ] Document the variables [on docs.altis](https://docs.altis-dxp.com/cloud/build-scripts/)
ref: https://github.com/humanmade/build-container/blob/master/build.sh#L7

**Comment by owaincuvelier** [comment]
just pushing this to the top as environment variables for deploy scripts has been [requested a couple times](https://humanmade.zendesk.com/agent/tickets/8500). It should also be quite quick to implement I believe.

**Comment by kovshenin** [comment]
Sample:

```
#!/bin/bash -e

#====================#
# Altis Build Script #
#====================#

set -e

# ENVIRONMENT=staging
ENVIRONMENT=development

# printenv
# echo "NAME: $NAME"
# echo "STACK NAME: $NAME"
# exit 1

if [ -f ".env.${ENVIRONMENT}" ]; then
  cp .env.${ENVIRONMENT} .env.local
fi

# Install npm dependencies
npm i

NODE_ENV=production npm run build
npm i --omit=dev --ignore-scripts --prefer-offline
```

Source: https://github.com/thehourglassgroup/react/blob/develop/.build-script

**Comment by owaincuvelier** [comment]
just an FYI, The Hour Glass team are waiting for this. I moved it to the top of our backlog list
