### ISSUE TITLE
Update build container to use PHP 8

### ISSUE THREAD

**Issue by veselala** [humanmade/altis-cloud#598]
### Description

The build container's PHP version should match the version the application is being run on as Composer needs to install the appropriate versions of packages for the version of PHP. Without this we could see errors not caught during the build process that only appear after deploy.

### Acceptance criteria

- [ ] Build container is running PHP 8
- [ ] Altis installs successfully on the new container
- [ ] The built application runs without errors after deploy

### Related Repositories
- https://github.com/humanmade/build-container

**Comment by roborourke** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Altis-5c378365e15075539771e4e3/issues/humanmade/altis-cloud/598?planning-poker) with ZenHub @jerico @sivanovhm @wisyhambolu @ferschubert-hm

**Comment by missjwo** [comment]
**PHP8 3 amigos notes:** 

Please be aware that there is a linked epic to update also the node and composer dependencies. See connected epic "[Update Build Container](https://app.zenhub.com/workspaces/altis-5c378365e15075539771e4e3/issues/humanmade/product-dev/795)".

There was a discussion about giving people choice over their build container version, but the discussion was inconclusive. @roborourke 's feeling is that this is too much work right now , so we are going to stick with updating the build container tools at the same time as updating PHP8.

**Comment by shadyvb** [comment]
Does this mean we should close this one instead in favor of https://app.zenhub.com/workspaces/altis-5c378365e15075539771e4e3/issues/humanmade/product-dev/651 which also tackles updating PHP8 in the build container ?

**Comment by roborourke** [comment]
Yeah good shout - it is covered there.
