### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cloud#616]
On [the cloud architecture page](https://docs.altis-dxp.com/cloud/architecture/) the architecture diagram image in the Overview section is missing (returns a 404).

## Screenshot

<img width="314" alt="Screenshot 2022-05-05 at 13 08 13" src="https://user-images.githubusercontent.com/208434/166911458-4a5590ac-694d-43e9-ae04-7beeefafa83a.png">

**Comment by roborourke** [comment]
This might be a general issue with SVG support on the dev docs site.

**Comment by robindevitt** [comment]
Should the dev docs site only be using jpeg / png images?

**Comment by robindevitt** [comment]
Yes, the line below from the [hooks.js](https://github.com/humanmade/altis-dev-docs-site/blob/main/src/hooks.js#L140) file needs `svg` added to it.

```JS
const imageExtensionRegex = /\.(png|jpeg|jpg|gif|bmp)$/;
```

**Comment by roborourke** [comment]
Nice spot, can you PR that update? Happy to review

**Comment by robindevitt** [comment]
The Altis docs site now supports SVG's.

URL containing an SVG image - https://docs.altis-dxp.com/cloud/architecture/
