### ISSUE TITLE
Link to "Debug in Altis Dashboard" is incorrect

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cloud#621]
Steps to reproduce:

1. Log in to an Altis Cloud site as an admin
2. Click the Query Monitor -> Debug in Altis Dashboard admin toolbar menu item
3. Observe that a blank screen is presented

The URL appears to be incorrect. It should be in the format: `https://dashboard.altis-dxp.com/#/i/<client>/e/<environment>/xray/trace/<trace>`

The current URL format is: `https://dashboard.altis-dxp.com/#/<region>/<environment>/xray/trace/<trace>`

Acceptance criteria:

- [x] Update the URL format of the "Debug in Altis Dashboard" link to the new structure `https://dashboard.altis-dxp.com/#/e/<environment>/xray/trace/<trace>`
- [x] Backport through to Altis v9

**Comment by roborourke** [comment]
It's the old URL but it should be redirecting iirc, cc @rmccue - possible regression in vantage?

**Comment by roborourke** [comment]
@robindevitt can you pick this one up after you've completed the 2 bug fixes currently in the sprint backlog?

**Comment by rmccue** [comment]
This is a regression in Vantage yes, related to the priority of the URLs in the root router

**Comment by robindevitt** [comment]
@roborourke Will do 👍🏼

**Comment by robindevitt** [comment]
@roborourke I have had a quick look at this. Based on the suggested URL:
> `https://dashboard.altis-dxp.com/#/i/<client>/e/<environment>/xray/trace/<trace>`

Is there a function to retrieve the `<client>`?

**Comment by roborourke** [comment]
Good question, I don’t think there is currently. We’ll need an infrastructure update to expose that as an environment variable, or we’ll need to make an API request to vantage.

Change focus for now, we’ll come back to this and try to fix it in vantage first. As Ryan noted it’s a regression

**Comment by rmccue** [comment]
The current link should work, or alternatively, you can use a short link of `#/e/<environment>/...` and that should also redirect.

The issue is the order of these components: https://github.com/humanmade/vantage/blob/master/src/App.js#L274-L291

The URLs there are overlapping, so the regex on the first route needs fixing to be more specific. I broke it in https://github.com/humanmade/vantage/commit/e18485a3133fd942817644c29590e91c78f376d8

**Comment by roborourke** [comment]
@robindevitt I updated the acceptance criteria per Ryan's comment, so no need to know the `<client>`

**Comment by robindevitt** [comment]
Issue is closed and backported

**Comment by johnbillion** [comment]
This seems to have regressed.

Example link from the "Debug in Altis Dashboard" admin menu item: https://dashboard.altis-dxp.com/#/eu-central-1/wuestpartner-prod-01/xray/trace/1-62d56c48-7401abda3ced9f3d2a45c3c9

Correct link: https://dashboard.altis-dxp.com/#/i/wuest-partner/e/wuestpartner-prod-01/xray/trace/1-62d56c48-7401abda3ced9f3d2a45c3c9

**Comment by roborourke** [comment]
cc @rmccue Vantage routes again?

**Comment by johnbillion** [comment]
Oh wait, is this tied to an Altis version? Wüest is on 11.0.0.

**Comment by roborourke** [comment]
Tied to a patch release but the PR was backported through to v9, it's dependent on the react router set up in vantage, we don't have all the info needed for the proper link on the servers currently.

**Comment by rmccue** [comment]
Verified this is no longer an issue.
