### ISSUE TITLE
Slow call to `Imagick::queryFormats`

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cloud#647]
Moving this into a public ticket from this support request: https://dashboard.altis-dxp.com/#/support/ticket/6864/.

There appears to be an intermittent issue where a call to `Imagick::queryFormats()` is slow (~500ms). It's unclear how often this happens but there are two links to affected XRay traces in the support ticket above.

<img width="564" alt="" src="https://user-images.githubusercontent.com/208434/179501794-1022b83e-5f8e-44db-a230-1fd6fe0394d6.png">

I did wonder if this call could be skipped entirely but unfortunately there doesn't appear to be any filters in WordPress core to prevent this call from occurring unless the `WP_Image_Editor_Imagick` class is replaced (using the `wp_image_editors` filter) by a custom one which doesn't perform this call.

Regardless, it might be worth investigating why this call is sometimes so slow.

**Comment by joehoyle** [comment]
Ah thanks John I also discovered this recently. Thankfully Joe McGill just got a patch committed to Core to cache this!
