### ISSUE TITLE
Subdomain installs break wp-admin/install.php healthcheck

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cloud#69]
It seems when specifying SUBDOMAIN install in multisite, the healthcheck requests to wp-admin/install.php break with a 500 error. This basically breaks the whole site as the healthcheck is required.

**Comment by roborourke** [comment]
Can we just throw an exception if this constant is specified? Given that it doesn't do anything any more? It'll get picked up in local dev at least.

**Comment by rmccue** [comment]
It does still have an effect in some parts of WP, we haven't quite fixed that up yet.

**Comment by joehoyle** [comment]
Yeah I think we need to support it, migrating projects can still have conditionals based off it- and given we don’t have the new create site ui in yet, there’s still some utility to the constant
