### ISSUE TITLE
/healthcheck on subsites report cron-canary failed

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-cloud#87]
If one is to use `/healthcheck` on a subsite, it'll report as failed because the option either doesn't exist for the subsite or if it does, it hasn't been run in a very long time. The second scenario is when a subsite on an installation used to be a main site, so the option is present in the subsite's option table.

Do we want `/healthcheck` to function for subsites?

------------

Acceptance criteria:

- [ ] Run `switch_to_blog()` to switch to main network site for the cavalcade healthcheck
- [ ] Visiting `/__healthcheck` on a subsite shows the `cron-canary` check as OK

**Comment by joehoyle** [comment]
If the cron hasn't run in a very long time, that sounds like a valid failure, and we should show the test as failed. Per https://github.com/humanmade/altis-cloud/blob/master/inc/healthcheck/inc/cavalcade/namespace.php it _should_ only exist on the main site though. I think we should have the healthcheck maybe do a `switch_to_blog` for the cron checking healthcheck though.

> Do we want /healthcheck to function for subsites?

I think so yes
